# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jovan Savic Web (UI/UX) Designer
email: contact@jovan.design
description: >- # this means to ignore newlines until "baseurl:"
  Jovan Savic is a creative problem solver. Jovan creates landing pages with conversions, and easy to use softwares.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
dribbble_username:  jovansavic
github_username:  johnofficial
instagram_username:  theesigner
linkedin_username:  jovansavic
twitter_username: theesigner
behance_username:  jovansavic
mail: contact@jovan.design
phone: 00381 66 8019 888
location: Serbia

#Footer
footer_text: designed and developed by jovan savic

#Home Page Strings

hero_title: Your search for a Web Designer Ends Here
hero_subtitle: "& Front-End Developer"
hero_text: Jovan is an entrepreneurial, business-first web designer who will efficiently design a product or a website for your startup/company.
hero_btn_01: Contact Me
hero_btn_01_link: /contact/
hero_btn_02: ABOUT ME
hero_btn_02_link: /about/
hero_image_url: hero_image_url

testimonials_title: They said about me
work_title: Case Studies
work_text: Read case studies and get insights on how projects can go from start to finish.

working_on_title: Jovan is working on
working_on_text: Some of the projects I’m working on are <a href="https://thetrack.app/" class="text-primary" target="_blank">thetrack</a>, owner.dog, and gosave.me. I’m creating simple, easy to use time tracking software for macOS, Windows, and Linux; website for easy returning pets to their owner; and cross-platform/cross-browser widget for saving cool articles to read later.


cta_title: Contact me
cta_text: Whatever you have project to work on, questions about my work or about me, or you just want to say Hi, you can contact me via e-mail address. If you are interested in working with me, let’s have a quick call to find if we are good fit togehter.
cta_btn_01: Send an e-mail
cta_btn_02: Make a call


#Post Page
client_name: Client name
client_location: Client location
what_they_do: What they do

# Projects Page
projects_title: Projects

#Process Page
process_title: Process
process_hero_img: me-table.jpg
process_intro: To provide high-quality work, with minimal surprises it’s important to have a clear process. This process is created from my, and others past experience, and I’m improving it since it’s created. Every time I find something that would improve the process and increase the chance of project success I’m updating this process.
process_testimonial: “The process is amazing, we worked together through it, and successfully finished development of my website. “
process_testimonial_name: Stefan Tomic
process_testimonial_title: Business Broker
process_testimonial_avatar: stefan-tomic.jpg

#About Page
about_title: About Jovan
about_intro: I help companies with web and/or app design, UI/UX problem solving, creating, improving or redesigning brand. Loving to talk with clients about their goals and to find how we can make a project successful. I can guarantee for a clear and professional process that will make our collaboration going smooth.
about_hero_img: me-table.jpg

about_skills_title: Skills
skill_text_01: As a designer, I’m creating beautiful, modern,  easy to use, websites and apps. It’s very important to create user centered design that are very intuitive.
skill_text_02: As a Front-End developer, I’m translating mine or someone else designs into pixel perfect websites. Some of the technologies I worked with are Angular 2, WordPress, jQuery, Ajax, Git, etc...
design: DESIGN
coding: CODING
design_skill_img: me-table.jpg
coding_skill_img: me-table.jpg

#Contact Page
contact_title: Contact
contact_text: Whatever you have project to work on, questions about my work or about me, or you just want to say Hi, you can contact me via e-mail address.
contact_cta: If you are interested in working with me, let’s have a quick conversation to find if we are good fit together.
contact_hero_img: me-table.jpg


# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


collections:
  projects:
    output: true
    permalink: /:path/

include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - frasco.config.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock
